# Generated by Django 5.0.1 on 2024-02-07 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='trabajo',
            new_name='serviciotecnico',
        ),
    ]
