# Generated by Django 5.0.1 on 2024-02-08 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_rename_trabajo_serviciotecnico'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectos',
            name='estado',
            field=models.CharField(default='A Realizar', max_length=50),
            preserve_default=False,
        ),
    ]
